### PR TITLE
GoFunc优化提议

### PR DESCRIPTION
**Pull request by qiangmzsx**
Fix the GoFunc function without recover panic

### CODE REVIEW

**Comment by qiangmzsx** [comment]
Fix the GoFunc function without recover panic

**Comment by zhiqiangxu** [comment]
I prefer not to recover inside GoFunc, it's up to the passed in `func`, in fact qrpc framework has do `recover` internally, this may cause recover multiple times.

BTW, GoFunc will be moved to https://github.com/zhiqiangxu/util in the future:)

**Comment by qiangmzsx** [comment]
Instead of relying on the passed function, it's better to treat it uniformly.such as  serveconn.go:301/func (sc *serveconn) readFrames() (err error)

**Comment by qiangmzsx** [comment]
GoFunc will be moved to https://github.com/zhiqiangxu/util in the future.It's a good idea.

**Comment by zhiqiangxu** [comment]
> Instead of relying on the passed function, it's better to treat it uniformly.such as serveconn.go:301/func (sc *serveconn) readFrames() (err error)

`readFrames` doesn't involve user code(`HandlerFunc`), so I'm confident there won't be any chance for `panic`, if there is, it should be fixed:)

I only put `recover` where user code is involved.

Maybe there can be another  `GoFuncWithRecover` or something like that though.

**Comment by zhiqiangxu** [comment]
> GoFunc will be moved to https://github.com/zhiqiangxu/util in the future.It's a good idea.But it's still worth fixing before the migration

In fact it's already there, I'll remove the `goroutine.go` from qrpc sometime later.

**Comment by qiangmzsx** [comment]
Then I will submit this code to https://github.com/zhiqiangxu/util, what do you think?

**Comment by zhiqiangxu** [comment]
我仔细想了下，还是不推荐在GoFunc里recover，因为能做的事情太少，只能打个日志。

个人更推荐的方式是，如果`func`内部有可能`panic`，那么就在`func`内部处理掉，这样在异常时做一些资源释放之类的收尾工作；如果交给外层，没法做实质性的收尾工作。

**Pull request closed without merging**
